version: '3'

services:
  api:
    image: registry.int.janelia.org/peeling/api:0.1.3
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./data:/retrieved_data
      - ./server:/app
      - ./results:/results
      - ./log:/log
    networks:
      - peeling-net
  client:
    image: registry.int.janelia.org/peeling/client:0.1.3
    build: ./client
    depends_on:
      - api
    ports:
      - "8002:80"
    networks:
      - peeling-net

networks:
  peeling-net:
    driver: bridge
